// Conteúdo real do Wesley Oliveira — bilíngue (PT/EN)
window.PORTFOLIO = {
  // Compartilhado (não traduz)
  name: "Wesley Oliveira",
  initials: "WO",
  yearsExp: "15+",
  links: {
    github: "github.com/WesleyOliveirajf",
    githubUrl: "https://github.com/WesleyOliveirajf",
    linkedin: "linkedin.com/in/wesleyoliveirajf",
    linkedinUrl: "https://www.linkedin.com/in/wesleyoliveirajf/",
    email: "wesleyinfo22@gmail.com",
    phone: "(32) 99989-5469",
  },

  // ────────────── PT ──────────────
  pt: {
    role: "Analista de Sistemas · Fullstack · IA & Automação",
    seniority: "Pleno",
    location: "Juiz de Fora, MG",
    available: "Disponível para oportunidades remotas, híbridas ou presenciais em Juiz de Fora/MG",

    intro: "Analista de Sistemas e Desenvolvedor Fullstack com mais de 15 anos em TI. Foco em automatizar processos com Python, integrar sistemas legados com tecnologias modernas e aplicar IA Generativa em produção.",

    longBio: [
      "Sou Analista de Sistemas com mais de 15 anos de experiência em TI, hoje atuando como Pleno na TORP Indústria Têxtil — onde evoluo o ERP SISPLAN, garanto a estabilidade da operação financeira e elimino trabalho manual da equipe com automações em Python.",
      "Tenho experiência sólida com bancos de dados SQL e PostgreSQL, criação de pipelines de dados e implementação de soluções com Inteligência Artificial Generativa via n8n e GPT-4o. Não é só teoria: meus agentes e automações estão em produção e entregam impacto mensurável.",
      "Tenho um perfil bridge: entendo tanto o lado técnico quanto as necessidades do negócio, facilitando a comunicação entre TI e áreas operacionais. Aprendo continuamente — atualmente faço especialização em IA para Desenvolvimento e estudo semanalmente Python, segurança e cloud.",
    ],

    stack: {
      "Linguagens":       ["Python", "Java", "JavaScript", "SQL", "HTML/CSS"],
      "Banco de Dados":   ["PostgreSQL", "SQL Server", "MySQL", "Stored Procedures", "ETL"],
      "Automação & IA":   ["n8n", "GPT-4o", "Agentes de IA", "RPA", "Python automation"],
      "Dev Tools":        ["Git/GitHub", "VS Code", "PyCharm", "IntelliJ", "Postman", "Supabase", "Vercel"],
      "Cloud & Infra":    ["VPS/Nginx", "Docker", "Linux", "MacOS", "Backup em nuvem"],
      "Dados & BI":       ["Power BI", "Excel avançado", "Power Query", "Pandas", "Análise estatística"],
      "Segurança":        ["LGPD", "Firewall", "WAF", "SIEM", "Auditoria de sistemas"],
      "Metodologias":     ["Scrum", "ITIL", "Documentação técnica", "Gestão de incidentes"],
    },

    projects: [
      {
        id: "automacao-torp",
        title: "Automações Python · ERP SISPLAN",
        kind: "Automação · Python",
        year: "2024 — presente",
        role: "Analista de Sistemas Pleno",
        summary: "Conjunto de automações em Python integradas ao ERP SISPLAN da TORP. Eliminaram 70% das tarefas manuais da equipe, liberando o time para atividades estratégicas.",
        stack: ["Python", "PostgreSQL", "ERP SISPLAN", "Cron/Scheduler"],
        metric: "−70% trabalho manual",
        hue: 140,
      },
      {
        id: "agentes-ia",
        title: "Agentes de IA · n8n + GPT-4o",
        kind: "IA Generativa · Automação",
        year: "2024 — presente",
        role: "Implementação fullstack",
        summary: "Integrações com IA Generativa e agentes autônomos via n8n + GPT-4o para respostas automáticas, análise de dados e fluxos internos da TORP. Em produção, não prova de conceito.",
        stack: ["n8n", "GPT-4o", "Agentes IA", "Python", "Webhooks"],
        metric: "agentes em produção",
        hue: 280,
      },
      {
        id: "dba-postgres",
        title: "Operação PostgreSQL · Financeiro",
        kind: "Database · Infra",
        year: "2024 — presente",
        role: "DBA",
        summary: "Gestão do banco financeiro da TORP: queries otimizadas, stored procedures, backups diários e integridade dos dados. ERP sem paradas críticas em toda a operação financeira.",
        stack: ["PostgreSQL", "SQL", "Linux", "Backup automatizado"],
        metric: "0 paradas críticas",
        hue: 210,
      },
      {
        id: "dashboards-vivo",
        title: "Dashboards Comerciais · Vivo Empresas",
        kind: "BI · Dados",
        year: "2023 — 2024",
        role: "Analista de Dados Jr.",
        summary: "Construção de dashboards Power BI e Excel para o time comercial da Vivo Empresas (via Nery Consultoria). Reduziram o tempo de análise em 50% e ajudaram a aumentar oportunidades comerciais em 32%.",
        stack: ["Power BI", "Excel", "SQL", "Power Query", "VBA"],
        metric: "−50% análise · +32% oportunidades",
        hue: 38,
      },
      {
        id: "pipeline-etl",
        title: "Pipelines ETL · SQL + VBA",
        kind: "Engenharia de Dados",
        year: "2023 — 2024",
        role: "Analista de Dados Jr.",
        summary: "Pipelines de extração e transformação de dados conectando bases corporativas a relatórios comerciais. SQL para o pesado, Power Query para modelagem, VBA para automação dos relatórios finais.",
        stack: ["SQL", "Power Query", "VBA", "Excel"],
        metric: "pipelines em produção",
        hue: 18,
      },
      {
        id: "lgpd-seguranca",
        title: "Conformidade LGPD · Acessos & Auditoria",
        kind: "Segurança da Informação",
        year: "2024 — presente",
        role: "Segurança & Compliance",
        summary: "Cuido da segurança da informação na TORP: controle de acessos, auditoria de sistemas e conformidade com a LGPD. Garante que os dados financeiros e operacionais estejam protegidos.",
        stack: ["LGPD", "Firewall", "WAF", "SIEM", "Auditoria"],
        metric: "conformidade ativa",
        hue: 0,
      },
    ],

    experience: [
      {
        period: "Jul/2024 — presente",
        role: "Analista de Sistemas Pleno",
        company: "TORP Indústria Têxtil",
        kind: "CLT · Presencial / Híbrido",
        bullets: [
          "Garanto que o ERP SISPLAN funcione sem paradas críticas — bugs e melhorias que impactam toda a operação financeira da empresa.",
          "Criei automações em Python que eliminaram 70% das tarefas manuais da equipe, liberando tempo para atividades estratégicas.",
          "Gerencio o banco PostgreSQL — queries otimizadas, stored procedures, backups diários e integridade dos dados financeiros.",
          "Desenvolvo integrações com IA Generativa e agentes automatizados via n8n + GPT-4o para respostas automáticas e análise de dados.",
          "Cuido da segurança da informação e conformidade com a LGPD, incluindo controle de acessos e auditoria de sistemas.",
        ],
      },
      {
        period: "Out/2023 — Jun/2024",
        role: "Analista de Dados Júnior",
        company: "Nery Consultoria / Vivo Empresas",
        kind: "PJ · Remoto",
        bullets: [
          "Construí dashboards em Power BI e Excel que reduziram o tempo de análise de dados em 50%.",
          "Criei pipelines de extração e transformação de dados com SQL, Power Query e VBA.",
          "Automatizações aumentaram em 32% as oportunidades comerciais identificadas pelo time.",
        ],
      },
      {
        period: "Jul/2017 — Set/2023",
        role: "Técnico de TI",
        company: "Lojas Tio Info",
        kind: "CLT · Presencial",
        bullets: [
          "Suporte técnico completo, manutenção de hardware/software e gestão de redes.",
          "Atendimento a clientes e operação de varejo de tecnologia.",
        ],
      },
      {
        period: "Jun/2009 — Jul/2017",
        role: "Técnico em Informática",
        company: "Getúlio Cyber Computadores",
        kind: "CLT · Presencial",
        bullets: [
          "Atendimento a clientes, manutenção de computadores e gestão de redes Windows e Linux.",
          "Primeira experiência sólida em TI — base que sustenta a carreira até hoje.",
        ],
      },
    ],

    education: [
      { period: "2026 — 2027 · em andamento ★", title: "Especialização em IA para Desenvolvimento", inst: "UniFatecie" },
      { period: "Jun/2025 — Dez/2025",          title: "Pós: IA Generativa — Inovação e Automação", inst: "UniFatecie" },
      { period: "Nov/2024 — Ago/2025",          title: "MBA em Gestão de Projetos de TI", inst: "UniFatecie" },
      { period: "Jul/2024 — Dez/2027 · em andamento", title: "Bacharelado em Sistemas de Informação", inst: "UniFatecie" },
      { period: "Nov/2024 — Dez/2026 · em andamento", title: "CST em Segurança da Informação", inst: "UNINTER" },
      { period: "Jul/2020 — Dez/2023",          title: "Tecnólogo em Análise e Desenvolvimento de Sistemas", inst: "UniFatecie" },
    ],

    certifications: [
      "Engenharia de Prompt — Asimov",
      "Criação de Agentes de IA com n8n",
      "Python Avançado — Alura",
      "PostgreSQL — Alura",
      "Cybersegurança — Alura",
      "DevOps e Linux CLI — Alura",
      "Segurança de Rede (Firewall, WAF, SIEM)",
      "Java Completo — Isiflix (Prof. Isidro Rodrigues)",
    ],

    differentials: [
      "Automações reais com impacto mensurável: 70% de redução de trabalho manual na TORP e 32% de aumento em oportunidades comerciais na Nery.",
      "Experiência prática com IA Generativa e agentes autônomos (n8n + GPT-4o-mini), não apenas teoria — aplicações rodando em produção.",
      "Perfil bridge: entendo tanto o lado técnico quanto as necessidades do negócio, facilitando a comunicação entre TI e áreas operacionais.",
      "Aprendizado contínuo: pós-graduação ativa + estudos semanais em Python, segurança e cloud.",
    ],

    // Strings de UI
    ui: {
      tagline: "Disponível para vagas CLT em modelo remoto ou híbrido. Respondo em até 24h.",
      yearsLabel: "anos em TI",
      yearsShort: "anos",
      canvasTitle: "Portfólio Wesley Oliveira",
      canvasSubtitle: "Três direções para uma vibe minimalista e elegante. Clique no ícone de expandir em cada artboard para abrir em tela cheia.",
      canvasPostIt: "Olá Wesley!\n\nMontei três direções\ndiferentes — todas\nminimalistas, mas com\npersonalidades distintas.\n\nClique no ícone ⤢ no\ncanto de cada artboard\npara visualizar em\ntela cheia.",
      canvasPageTitle: "Portfólio · Wesley Oliveira — 3 direções",
      langSwitchAria: "Idioma: Português ou Inglês",
      openTo: "aberto a CLT",
      sectionAbout: "Sobre()",
      sectionAboutMeta: "// quem sou eu",
      sectionWork: "trabalhos[]",
      sectionWorkMeta: (n) => `// ${n} projetos selecionados`,
      sectionCv: "carreira.timeline()",
      sectionCvMeta: (n) => `// ${n} posições`,
      sectionDiff: "diferenciais()",
      sectionDiffMeta: "// por que eu",
      sectionStack: "stack.json",
      sectionStackMeta: (n) => `// ${n} itens`,
      sectionContact: "contato()",
      sectionContactMeta: "// fala comigo",
      navAbout: "sobre",
      navWork: "trabalhos",
      navCv: "cv",
      navWhyMe: "por_que",
      navStack: "stack",
      navContact: "contato",
      openToWork: "● disponível",
      bioContact: "contato direto",
      education: "// formação",
      certs: "// certificações",
      downloadCv: "↓ baixar.cv.pdf",
      sendEmail: "envie.email →",
      links: "// links",
      readMore: "ler →",
      caseStudy: "case_study",
      heroDirectContact: "contato direto",
      footerExit: "$ exit 0",
      readme: "última atualização: mai/2026",
      jsonRole: "Analista de Sistemas",
      jsonFocus: "Fullstack · IA · Automação",
      jsonLevel: "Pleno",
      jsonBased: "Juiz de Fora, MG",
      jsonModel: "CLT/PJ · remoto/híbrido",
      heroLoc: "Juiz de Fora - MG, Brasil",
      heroStack: "Python · Java · Node · SQL",
      contactHeadline1: "olá@",
      contactHeadline2: "wesley.dev",
    },

    tpl: {
      editorial: {
        portfolioVer: "Portfólio · MMXXVI",
        avail: "Disponível",
        sectionAbout: "Sobre",
        loc: "Localização",
        exp: "Experiência",
        status: "Status",
        statusVal: "Vagas CLT",
        sectionProjects: "Projetos selecionados",
        sectionExp: "Experiência profissional",
        sectionStack: "Stack e habilidades",
        contactNum: "V.",
        contact: "Contato",
        ctaLets: "Vamos ",
        ctaTalk: "conversar",
        ctaQ: "?",
        downloadCv: "↓ Baixar CV (PDF)",
        footer: "✦   Wesley Oliveira   ✦   Portfólio · MMXXVI   ✦",
      },
      swiss: {
        nav01: "01 / Sobre",
        nav02: "02 / Trabalho",
        nav03: "03 / Carreira",
        nav04: "04 / Stack",
        nav05: "05 / Contato",
        openBadge: "● Disponível",
        folioLine: "Portfólio · v.04",
        heroEn: false,
        heroL1: "Desen-",
        heroL2: "volvedor",
        heroL3: "Fullstack",
        summaryLabel: "Resumo —",
        metaLoc: "Localização",
        metaExp: "Experiência",
        metaModel: "Modelo",
        metaLang: "Idiomas",
        metaEdu: "Formação",
        metaLangVal: "Português · Inglês (B2)",
        metaEduVal: "Sistemas de Informação",
        metaModelVal: "CLT · Remoto/Híbrido",
        sh01sub: "WHO/WHAT/WHY",
        sh01: "Sobre",
        sh02: "Trabalho selecionado",
        sh03: "Carreira",
        sh04: "Stack",
        sh05: "Contato",
        sh05sub: "ABERTO · CLT",
        ctaL1: "Vamos",
        ctaL2: "trabalhar",
        ctaL3: "juntos.",
        dlCv: "↓ Baixar CV",
        sendMail: "Enviar email →",
        footerMid: "Wesley Oliveira · Desenvolvedor Fullstack ·",
        footerTop: "↑ Topo",
        sh02Sub: (n) => `${n} projetos / 2022 — 2025`,
        sh03Sub: (n) => `${n} posições`,
        sh04Sub: (n) => `${n} ferramentas`,
        topTo: "Topo",
      },
    },
  },

  // ────────────── EN ──────────────
  en: {
    role: "Systems Analyst · Fullstack · AI & Automation",
    seniority: "Mid-level",
    location: "Juiz de Fora, MG, Brazil",
    available: "Open to remote, hybrid, and on-site roles in Juiz de Fora/MG",

    intro: "Systems Analyst and Fullstack Developer with 15+ years in IT. Focused on automating processes with Python, integrating legacy systems with modern tech, and shipping Generative AI to production.",

    longBio: [
      "I'm a Systems Analyst with 15+ years of IT experience, currently working as a mid-level engineer at TORP Indústria Têxtil — where I evolve the SISPLAN ERP, keep the financial operation stable, and remove manual work from the team with Python automations.",
      "Solid background in SQL/PostgreSQL databases, data pipelines, and Generative AI solutions via n8n and GPT-4o. Not just theory: my agents and automations run in production and deliver measurable impact.",
      "I have a bridge profile: I understand both the technical side and business needs, easing communication between IT and operational teams. I'm a continuous learner — currently in a specialization in AI for Development and studying Python, security, and cloud weekly.",
    ],

    stack: {
      "Languages":        ["Python", "Java", "JavaScript", "SQL", "HTML/CSS"],
      "Databases":        ["PostgreSQL", "SQL Server", "MySQL", "Stored Procedures", "ETL"],
      "Automation & AI":  ["n8n", "GPT-4o", "AI Agents", "RPA", "Python automation"],
      "Dev Tools":        ["Git/GitHub", "VS Code", "PyCharm", "IntelliJ", "Postman", "Supabase", "Vercel"],
      "Cloud & Infra":    ["VPS/Nginx", "Docker", "Linux", "MacOS", "Cloud backup"],
      "Data & BI":        ["Power BI", "Advanced Excel", "Power Query", "Pandas", "Statistical analysis"],
      "Security":         ["LGPD", "Firewall", "WAF", "SIEM", "Systems auditing"],
      "Methodologies":    ["Scrum", "ITIL", "Technical documentation", "Incident management"],
    },

    projects: [
      {
        id: "automacao-torp",
        title: "Python Automations · SISPLAN ERP",
        kind: "Automation · Python",
        year: "2024 — present",
        role: "Mid-level Systems Analyst",
        summary: "A set of Python automations integrated with TORP's SISPLAN ERP. Removed 70% of the team's manual tasks, freeing the squad for strategic work.",
        stack: ["Python", "PostgreSQL", "SISPLAN ERP", "Cron/Scheduler"],
        metric: "−70% manual work",
        hue: 140,
      },
      {
        id: "agentes-ia",
        title: "AI Agents · n8n + GPT-4o",
        kind: "Generative AI · Automation",
        year: "2024 — present",
        role: "Fullstack implementation",
        summary: "Generative AI integrations and autonomous agents via n8n + GPT-4o for automated replies, data analysis, and internal flows at TORP. In production — not a proof of concept.",
        stack: ["n8n", "GPT-4o", "AI Agents", "Python", "Webhooks"],
        metric: "agents in production",
        hue: 280,
      },
      {
        id: "dba-postgres",
        title: "PostgreSQL Operations · Finance",
        kind: "Database · Infra",
        year: "2024 — present",
        role: "DBA",
        summary: "Management of TORP's finance database: optimized queries, stored procedures, daily backups, and data integrity. Zero critical downtime across the entire financial operation.",
        stack: ["PostgreSQL", "SQL", "Linux", "Automated backup"],
        metric: "0 critical downtime",
        hue: 210,
      },
      {
        id: "dashboards-vivo",
        title: "Commercial Dashboards · Vivo Empresas",
        kind: "BI · Data",
        year: "2023 — 2024",
        role: "Jr. Data Analyst",
        summary: "Built Power BI and Excel dashboards for the Vivo Empresas sales team (via Nery Consultoria). Cut analysis time by 50% and helped grow commercial opportunities by 32%.",
        stack: ["Power BI", "Excel", "SQL", "Power Query", "VBA"],
        metric: "−50% analysis · +32% opportunities",
        hue: 38,
      },
      {
        id: "pipeline-etl",
        title: "ETL Pipelines · SQL + VBA",
        kind: "Data Engineering",
        year: "2023 — 2024",
        role: "Jr. Data Analyst",
        summary: "Extraction and transformation pipelines connecting corporate databases to commercial reports. SQL for the heavy lifting, Power Query for modeling, VBA for final report automation.",
        stack: ["SQL", "Power Query", "VBA", "Excel"],
        metric: "pipelines in production",
        hue: 18,
      },
      {
        id: "lgpd-seguranca",
        title: "LGPD Compliance · Access & Auditing",
        kind: "Information Security",
        year: "2024 — present",
        role: "Security & Compliance",
        summary: "I own information security at TORP: access control, systems auditing, and LGPD compliance. Ensures financial and operational data stays protected.",
        stack: ["LGPD", "Firewall", "WAF", "SIEM", "Auditing"],
        metric: "active compliance",
        hue: 0,
      },
    ],

    experience: [
      {
        period: "Jul/2024 — present",
        role: "Mid-level Systems Analyst",
        company: "TORP Indústria Têxtil",
        kind: "Full-time · On-site / Hybrid",
        bullets: [
          "Keep the SISPLAN ERP running with zero critical downtime — bugs and improvements that impact the entire financial operation.",
          "Built Python automations that removed 70% of the team's manual tasks, freeing time for strategic work.",
          "Manage the PostgreSQL database — optimized queries, stored procedures, daily backups, and financial data integrity.",
          "Develop Generative AI integrations and automated agents with n8n + GPT-4o for automated replies and data analysis.",
          "Own information security and LGPD compliance, including access control and systems auditing.",
        ],
      },
      {
        period: "Oct/2023 — Jun/2024",
        role: "Junior Data Analyst",
        company: "Nery Consultoria / Vivo Empresas",
        kind: "Contractor · Remote",
        bullets: [
          "Built Power BI and Excel dashboards that cut data analysis time by 50%.",
          "Created data extraction and transformation pipelines with SQL, Power Query, and VBA.",
          "Automations grew commercial opportunities identified by the team by 32%.",
        ],
      },
      {
        period: "Jul/2017 — Sep/2023",
        role: "IT Technician",
        company: "Lojas Tio Info",
        kind: "Full-time · On-site",
        bullets: [
          "Complete tech support, hardware/software maintenance, and network management.",
          "Customer service and operation of a tech retail store.",
        ],
      },
      {
        period: "Jun/2009 — Jul/2017",
        role: "Computer Technician",
        company: "Getúlio Cyber Computadores",
        kind: "Full-time · On-site",
        bullets: [
          "Customer service, computer maintenance, and Windows/Linux network management.",
          "First solid IT experience — the foundation my career still stands on.",
        ],
      },
    ],

    education: [
      { period: "2026 — 2027 · in progress ★", title: "Specialization in AI for Development", inst: "UniFatecie" },
      { period: "Jun/2025 — Dec/2025",          title: "Postgrad: Generative AI — Innovation & Automation", inst: "UniFatecie" },
      { period: "Nov/2024 — Aug/2025",          title: "MBA in IT Project Management", inst: "UniFatecie" },
      { period: "Jul/2024 — Dec/2027 · in progress", title: "Bachelor's in Information Systems", inst: "UniFatecie" },
      { period: "Nov/2024 — Dec/2026 · in progress", title: "Tech Degree in Information Security", inst: "UNINTER" },
      { period: "Jul/2020 — Dec/2023",          title: "Tech Degree in Systems Analysis & Development", inst: "UniFatecie" },
    ],

    certifications: [
      "Prompt Engineering — Asimov",
      "AI Agents with n8n",
      "Advanced Python — Alura",
      "PostgreSQL — Alura",
      "Cybersecurity — Alura",
      "DevOps & Linux CLI — Alura",
      "Network Security (Firewall, WAF, SIEM)",
      "Complete Java — Isiflix (Prof. Isidro Rodrigues)",
    ],

    differentials: [
      "Real automations with measurable impact: 70% reduction in manual work at TORP and 32% increase in commercial opportunities at Nery.",
      "Hands-on experience with Generative AI and autonomous agents (n8n + GPT-4o-mini), not just theory — applications running in production.",
      "Bridge profile: I understand both the technical side and the business needs, easing communication between IT and operational teams.",
      "Continuous learning: active postgrad + weekly studies in Python, security, and cloud.",
    ],

    ui: {
      tagline: "Open to full-time roles, remote or hybrid. I reply within 24h.",
      yearsLabel: "yrs in IT",
      yearsShort: "yrs",
      canvasTitle: "Wesley Oliveira — Portfolio",
      canvasSubtitle: "Three minimalist, elegant directions. Click the expand icon on each artboard to open it fullscreen.",
      canvasPostIt: "Hi Wesley!\n\nHere are three different\ndirections — all\nminimalist, each with its\nown personality.\n\nClick the ⤢ icon on\neach artboard to view it\nfullscreen.",
      canvasPageTitle: "Portfolio · Wesley Oliveira — 3 concepts",
      langSwitchAria: "Language: Portuguese or English",
      openTo: "open to full-time",
      sectionAbout: "about()",
      sectionAboutMeta: "// who i am",
      sectionWork: "work[]",
      sectionWorkMeta: (n) => `// ${n} selected projects`,
      sectionCv: "career.timeline()",
      sectionCvMeta: (n) => `// ${n} positions`,
      sectionDiff: "why_me()",
      sectionDiffMeta: "// differentials",
      sectionStack: "stack.json",
      sectionStackMeta: (n) => `// ${n} items`,
      sectionContact: "contact()",
      sectionContactMeta: "// say hi",
      navAbout: "about",
      navWork: "work",
      navCv: "cv",
      navWhyMe: "why_me",
      navStack: "stack",
      navContact: "contact",
      openToWork: "● open_to_work",
      bioContact: "direct contact",
      education: "// education",
      certs: "// certifications",
      downloadCv: "↓ download.cv.pdf",
      sendEmail: "send.email →",
      links: "// links",
      readMore: "read →",
      caseStudy: "case_study",
      heroDirectContact: "direct contact",
      footerExit: "$ exit 0",
      readme: "last update: may/2026",
      jsonRole: "Systems Analyst",
      jsonFocus: "Fullstack · AI · Automation",
      jsonLevel: "Mid-level",
      jsonBased: "Juiz de Fora, MG, Brazil",
      jsonModel: "Full-time/Contract · remote/hybrid",
      heroLoc: "Juiz de Fora - MG, Brazil",
      heroStack: "Python · Java · Node · SQL",
      contactHeadline1: "hello@",
      contactHeadline2: "wesley.dev",
    },

    tpl: {
      editorial: {
        portfolioVer: "Portfolio · MMXXVI",
        avail: "Available",
        sectionAbout: "About",
        loc: "Location",
        exp: "Experience",
        status: "Status",
        statusVal: "Open to full-time",
        sectionProjects: "Selected projects",
        sectionExp: "Professional experience",
        sectionStack: "Stack & skills",
        contactNum: "V.",
        contact: "Contact",
        ctaLets: "Let's ",
        ctaTalk: "talk",
        ctaQ: ".",
        downloadCv: "↓ Download résumé (PDF)",
        footer: "✦   Wesley Oliveira   ✦   Portfolio · MMXXVI   ✦",
      },
      swiss: {
        nav01: "01 / About",
        nav02: "02 / Work",
        nav03: "03 / Career",
        nav04: "04 / Stack",
        nav05: "05 / Contact",
        openBadge: "● Available",
        folioLine: "Portfolio · v.04",
        heroEn: true,
        heroL1: "Fullstack",
        heroL2: "Developer",
        heroL3: "",
        summaryLabel: "Summary —",
        metaLoc: "Location",
        metaExp: "Experience",
        metaModel: "Model",
        metaLang: "Languages",
        metaEdu: "Education",
        metaLangVal: "Portuguese · English (B2)",
        metaEduVal: "Information Systems",
        metaModelVal: "Full-time · Remote/Hybrid",
        sh01sub: "WHO/WHAT/WHY",
        sh01: "About",
        sh02: "Selected work",
        sh03: "Career",
        sh04: "Stack",
        sh05: "Contact",
        sh05sub: "OPEN · FULL-TIME",
        ctaL1: "Let's",
        ctaL2: "build",
        ctaL3: "together.",
        dlCv: "↓ Download CV",
        sendMail: "Send email →",
        footerMid: "Wesley Oliveira · Fullstack Developer ·",
        footerTop: "↑ Top",
        sh02Sub: (n) => `${n} cases / 2022 — 2025`,
        sh03Sub: (n) => `${n} positions`,
        sh04Sub: (n) => `${n} tools`,
        topTo: "Top",
      },
    },
  },
};
